### ISSUE TITLE
how to update it 

### ISSUE THREAD

**Issue by Andrius86** [evanhyd/CSGO_SneakyKitty#1]
the cheat dosen't work how to update it

**Comment by evanhyd** [comment]
This is not a valid question.
Please write down the exact details of how the cheat doesn't work, for example, which feature broke?
How to update it? There is plenty of information on Unknowncheats, especially in the reverse struct section: https://www.unknowncheats.me/forum/counterstrike-global-offensive/103220-counterstrike-global-offensive-reversal-structs-offsets-801.html

After briefly looking through the recent posts on UC, it seems CSGO has again updated the C_Input class, you may have to fix the padding in that class yourself. Information is again available online
